version: '3'

volumes:
  webchat_nodejs_db:
  
services:
  webchat-server_db:
    image: mysql:5.6
    container_name: webchat-server_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - webchat_nodejs_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
